language: swift

osx_image: xcode10.1

cache: cocoapods

before_install:
- gem install cocoapods # Since Travis is not always on latest version

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace SortingHat.xcworkspace -scheme SortingHat ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
- pod lib lint
